// <auto-generated />
using System;
using QmaService.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace QmaService.Migrations
{
    [DbContext(typeof(QmaDbContext))]
    partial class QmaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QmaService.Models.MeasurementHistoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ErrorMessage").HasColumnType("text");
                    b.Property<bool>("HasError").HasColumnType("boolean");
                    b.Property<string>("Op1Category").IsRequired().HasMaxLength(50).HasColumnType("character varying(50)");
                    b.Property<string>("Op1Unit").IsRequired().HasMaxLength(50).HasColumnType("character varying(50)");
                    b.Property<double>("Op1Value").HasColumnType("double precision");
                    b.Property<string>("Op2Category").HasMaxLength(50).HasColumnType("character varying(50)");
                    b.Property<string>("Op2Unit").HasMaxLength(50).HasColumnType("character varying(50)");
                    b.Property<double?>("Op2Value").HasColumnType("double precision");
                    b.Property<string>("OperationType").IsRequired().HasMaxLength(50).HasColumnType("character varying(50)");
                    b.Property<string>("ResultCategory").HasMaxLength(50).HasColumnType("character varying(50)");
                    b.Property<string>("ResultUnit").HasMaxLength(50).HasColumnType("character varying(50)");
                    b.Property<double?>("ResultValue").HasColumnType("double precision");
                    b.Property<DateTime>("Timestamp").HasColumnType("timestamp with time zone");
                    b.Property<int?>("UserId").HasColumnType("integer");

                    b.HasKey("Id");
                    b.ToTable("measurements");
                });
#pragma warning restore 612, 618
        }
    }
}
